services:
  neurai-blockbook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockbook
    volumes:
      - neurai-blockbook-data:/data
      - neurai-blockbook-logs:/data/blockbook/logs
    restart: unless-stopped
    ports:
      - "9168:9168"
    environment:
      - BLOCKBOOK_PUBLIC_PORT=9168
      - BLOCKBOOK_INTERNAL_PORT=9068
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9168"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - neurai_blockbook_net 

volumes:
  neurai-blockbook-data:
  neurai-blockbook-logs:

networks:
  neurai_blockbook_net:
    driver: bridge
